version: '3'

services:
  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anivicio
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 0.5s
      retries: 5